"""Initial migration.

Revision ID: 890f48b4cc12
Revises: 
Create Date: 2024-07-13 00:30:59.999866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f48b4cc12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('time_moved', sa.DateTime(), nullable=False),
    sa.Column('drowsiness_state', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=True),
    sa.Column('car_type', sa.String(length=120), nullable=True),
    sa.Column('driver', sa.String(length=120), nullable=True),
    sa.Column('reg_year', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('data')
    # ### end Alembic commands ###
